// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// gender type
type GenderType int32

const (
	GenderType_SECRET GenderType = 0
	GenderType_FEMALE GenderType = 1
	GenderType_MALE   GenderType = 2
)

var GenderType_name = map[int32]string{
	0: "SECRET",
	1: "FEMALE",
	2: "MALE",
}

var GenderType_value = map[string]int32{
	"SECRET": 0,
	"FEMALE": 1,
	"MALE":   2,
}

func (x GenderType) String() string {
	return proto.EnumName(GenderType_name, int32(x))
}

func (GenderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type LoginResult int32

const (
	LoginResult_SUCCESS        LoginResult = 0
	LoginResult_PSWERROR       LoginResult = 1
	LoginResult_USERNOTEXIST   LoginResult = 2
	LoginResult_USERALDYONLINE LoginResult = 3
	LoginResult_INTERERROR     LoginResult = 4
)

var LoginResult_name = map[int32]string{
	0: "SUCCESS",
	1: "PSWERROR",
	2: "USERNOTEXIST",
	3: "USERALDYONLINE",
	4: "INTERERROR",
}

var LoginResult_value = map[string]int32{
	"SUCCESS":        0,
	"PSWERROR":       1,
	"USERNOTEXIST":   2,
	"USERALDYONLINE": 3,
	"INTERERROR":     4,
}

func (x LoginResult) String() string {
	return proto.EnumName(LoginResult_name, int32(x))
}

func (LoginResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type LogoutResult int32

const (
	LogoutResult_LOGOUTSUCCESS    LogoutResult = 0
	LogoutResult_LOGOUTINTERERROR LogoutResult = 1
)

var LogoutResult_name = map[int32]string{
	0: "LOGOUTSUCCESS",
	1: "LOGOUTINTERERROR",
}

var LogoutResult_value = map[string]int32{
	"LOGOUTSUCCESS":    0,
	"LOGOUTINTERERROR": 1,
}

func (x LogoutResult) String() string {
	return proto.EnumName(LogoutResult_name, int32(x))
}

func (LogoutResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

type ChatMsgType int32

const (
	ChatMsgType_PRIVATE_CHAT ChatMsgType = 0
	ChatMsgType_GROUP_CHAT   ChatMsgType = 1
)

var ChatMsgType_name = map[int32]string{
	0: "PRIVATE_CHAT",
	1: "GROUP_CHAT",
}

var ChatMsgType_value = map[string]int32{
	"PRIVATE_CHAT": 0,
	"GROUP_CHAT":   1,
}

func (x ChatMsgType) String() string {
	return proto.EnumName(ChatMsgType_name, int32(x))
}

func (ChatMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

// user info
type UserInfo struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string     `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32     `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender               GenderType `protobuf:"varint,5,opt,name=gender,proto3,enum=protos.GenderType" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetGender() GenderType {
	if m != nil {
		return m.Gender
	}
	return GenderType_SECRET
}

// sign up request
type SignupRequest struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32     `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender               GenderType `protobuf:"varint,3,opt,name=gender,proto3,enum=protos.GenderType" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignupRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SignupRequest) GetGender() GenderType {
	if m != nil {
		return m.Gender
	}
	return GenderType_SECRET
}

// sign up response
type SignupResponse struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SignupResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SignupResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// login request
type LoginRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// login response
type LoginResponse struct {
	Result               LoginResult `protobuf:"varint,1,opt,name=result,proto3,enum=protos.LoginResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResult() LoginResult {
	if m != nil {
		return m.Result
	}
	return LoginResult_SUCCESS
}

// login out
type LogoutRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// logout response
type LogoutResponse struct {
	Result               LogoutResult `protobuf:"varint,1,opt,name=result,proto3,enum=protos.LogoutResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetResult() LogoutResult {
	if m != nil {
		return m.Result
	}
	return LogoutResult_LOGOUTSUCCESS
}

type ChatMsg struct {
	MsgId                uint32      `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgType              ChatMsgType `protobuf:"varint,2,opt,name=msgType,proto3,enum=protos.ChatMsgType" json:"msgType,omitempty"`
	MsgFrom              uint64      `protobuf:"varint,3,opt,name=msgFrom,proto3" json:"msgFrom,omitempty"`
	MsgTo                uint64      `protobuf:"varint,4,opt,name=msgTo,proto3" json:"msgTo,omitempty"`
	Data                 string      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *ChatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsg.Unmarshal(m, b)
}
func (m *ChatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsg.Marshal(b, m, deterministic)
}
func (m *ChatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsg.Merge(m, src)
}
func (m *ChatMsg) XXX_Size() int {
	return xxx_messageInfo_ChatMsg.Size(m)
}
func (m *ChatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsg proto.InternalMessageInfo

func (m *ChatMsg) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatMsg) GetMsgType() ChatMsgType {
	if m != nil {
		return m.MsgType
	}
	return ChatMsgType_PRIVATE_CHAT
}

func (m *ChatMsg) GetMsgFrom() uint64 {
	if m != nil {
		return m.MsgFrom
	}
	return 0
}

func (m *ChatMsg) GetMsgTo() uint64 {
	if m != nil {
		return m.MsgTo
	}
	return 0
}

func (m *ChatMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// client and server heartbeat msg
type HeartbeatMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatMsg) Reset()         { *m = HeartbeatMsg{} }
func (m *HeartbeatMsg) String() string { return proto.CompactTextString(m) }
func (*HeartbeatMsg) ProtoMessage()    {}
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *HeartbeatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatMsg.Unmarshal(m, b)
}
func (m *HeartbeatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatMsg.Marshal(b, m, deterministic)
}
func (m *HeartbeatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatMsg.Merge(m, src)
}
func (m *HeartbeatMsg) XXX_Size() int {
	return xxx_messageInfo_HeartbeatMsg.Size(m)
}
func (m *HeartbeatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatMsg proto.InternalMessageInfo

func (m *HeartbeatMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// client and server heartbeat replay msg
type HeartbeatReplyMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReplyMsg) Reset()         { *m = HeartbeatReplyMsg{} }
func (m *HeartbeatReplyMsg) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReplyMsg) ProtoMessage()    {}
func (*HeartbeatReplyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *HeartbeatReplyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReplyMsg.Unmarshal(m, b)
}
func (m *HeartbeatReplyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReplyMsg.Marshal(b, m, deterministic)
}
func (m *HeartbeatReplyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReplyMsg.Merge(m, src)
}
func (m *HeartbeatReplyMsg) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReplyMsg.Size(m)
}
func (m *HeartbeatReplyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReplyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReplyMsg proto.InternalMessageInfo

func (m *HeartbeatReplyMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.GenderType", GenderType_name, GenderType_value)
	proto.RegisterEnum("protos.LoginResult", LoginResult_name, LoginResult_value)
	proto.RegisterEnum("protos.LogoutResult", LogoutResult_name, LogoutResult_value)
	proto.RegisterEnum("protos.ChatMsgType", ChatMsgType_name, ChatMsgType_value)
	proto.RegisterType((*UserInfo)(nil), "protos.UserInfo")
	proto.RegisterType((*SignupRequest)(nil), "protos.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "protos.SignupResponse")
	proto.RegisterType((*LoginRequest)(nil), "protos.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protos.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "protos.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "protos.LogoutResponse")
	proto.RegisterType((*ChatMsg)(nil), "protos.ChatMsg")
	proto.RegisterType((*HeartbeatMsg)(nil), "protos.HeartbeatMsg")
	proto.RegisterType((*HeartbeatReplyMsg)(nil), "protos.HeartbeatReplyMsg")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x8b, 0xd3, 0x50,
	0x10, 0xdd, 0x9b, 0x64, 0xfb, 0x31, 0x6d, 0x43, 0x76, 0x2c, 0x12, 0x7c, 0xb1, 0x04, 0x84, 0x52,
	0xb5, 0xc2, 0xfa, 0x20, 0x88, 0x08, 0xa5, 0xde, 0xed, 0x06, 0xba, 0x4d, 0xb9, 0x49, 0xfd, 0x78,
	0x51, 0xb2, 0xe4, 0x1a, 0x0b, 0xcd, 0x87, 0xb9, 0x29, 0xb2, 0xff, 0xc0, 0x67, 0x7f, 0xb1, 0xe4,
	0x26, 0xe9, 0x66, 0xb5, 0x22, 0xfb, 0x94, 0x99, 0xe1, 0xcc, 0x9c, 0xb9, 0x67, 0x4e, 0xa0, 0x1b,
	0x89, 0x70, 0x9a, 0x66, 0x49, 0x9e, 0x60, 0x4b, 0x7e, 0x84, 0xf5, 0x93, 0x40, 0x67, 0x23, 0x78,
	0x66, 0xc7, 0x5f, 0x13, 0xd4, 0x41, 0xd9, 0x06, 0x26, 0x19, 0x91, 0xb1, 0xc6, 0x94, 0x6d, 0x80,
	0x8f, 0xa0, 0x93, 0xfa, 0x42, 0xfc, 0x48, 0xb2, 0xc0, 0x54, 0x46, 0x64, 0xdc, 0x65, 0x87, 0x1c,
	0x11, 0xb4, 0xd8, 0x8f, 0xb8, 0xa9, 0xca, 0xba, 0x8c, 0xd1, 0x00, 0xd5, 0x0f, 0xb9, 0xa9, 0x8d,
	0xc8, 0x78, 0xc0, 0x8a, 0x10, 0x27, 0xd0, 0x0a, 0x79, 0x1c, 0xf0, 0xcc, 0x3c, 0x1d, 0x91, 0xb1,
	0x7e, 0x8e, 0x25, 0xbd, 0x98, 0x2e, 0x64, 0xd5, 0xbb, 0x49, 0x39, 0xab, 0x10, 0x96, 0x0f, 0x03,
	0x77, 0x1b, 0xc6, 0xfb, 0x94, 0xf1, 0xef, 0x7b, 0x2e, 0xf2, 0x03, 0x05, 0xf9, 0x9b, 0x42, 0x39,
	0x46, 0xa1, 0xfe, 0x97, 0xc2, 0x03, 0xbd, 0xa6, 0x10, 0x69, 0x12, 0x0b, 0x8e, 0x0f, 0xa1, 0x95,
	0x71, 0xb1, 0xdf, 0xe5, 0x92, 0x65, 0xc0, 0xaa, 0xac, 0x92, 0x42, 0x39, 0x2a, 0x85, 0x7a, 0x57,
	0x0a, 0xeb, 0x35, 0xf4, 0x97, 0x49, 0xb8, 0x8d, 0xeb, 0xbd, 0xef, 0x21, 0xa3, 0xf5, 0x06, 0x06,
	0x55, 0x6f, 0xb5, 0xd0, 0xd3, 0x3b, 0x0b, 0xe9, 0xe7, 0x0f, 0xea, 0xe7, 0xd4, 0xb0, 0xfd, 0x2e,
	0xaf, 0xb7, 0xb4, 0x1e, 0xcb, 0xee, 0x64, 0x9f, 0xff, 0x83, 0xda, 0x7a, 0x0b, 0x7a, 0x0d, 0xa8,
	0xe6, 0x3f, 0xfb, 0x63, 0xfe, 0xb0, 0x31, 0xbf, 0xc4, 0x35, 0x09, 0x7e, 0x11, 0x68, 0xcf, 0xbf,
	0xf9, 0xf9, 0x95, 0x08, 0x71, 0x08, 0xa7, 0x91, 0x08, 0xed, 0xa0, 0x52, 0xaa, 0x4c, 0xf0, 0x39,
	0xb4, 0x23, 0x11, 0x16, 0x2a, 0xcb, 0xb7, 0x35, 0x16, 0xae, 0xfa, 0xe4, 0x01, 0x6a, 0x0c, 0x9a,
	0x12, 0x7e, 0x91, 0x25, 0x91, 0x94, 0x51, 0x63, 0x75, 0x5a, 0x8d, 0xf7, 0x12, 0x69, 0x1f, 0x8d,
	0x95, 0x49, 0xe1, 0x81, 0xc0, 0xcf, 0x7d, 0x69, 0x9f, 0x2e, 0x93, 0xb1, 0x35, 0x82, 0xfe, 0x25,
	0xf7, 0xb3, 0xfc, 0x9a, 0x97, 0x8b, 0x19, 0xa0, 0x46, 0x22, 0xac, 0x6c, 0x52, 0x84, 0xd6, 0x13,
	0x38, 0x3b, 0x20, 0x18, 0x4f, 0x77, 0x37, 0x47, 0x61, 0x93, 0x29, 0xc0, 0xad, 0x49, 0x10, 0xa0,
	0xe5, 0xd2, 0x39, 0xa3, 0x9e, 0x71, 0x52, 0xc4, 0x17, 0xf4, 0x6a, 0xb6, 0xa4, 0x06, 0xc1, 0x0e,
	0x68, 0x32, 0x52, 0x26, 0x9f, 0xa1, 0xd7, 0xb8, 0x02, 0xf6, 0xa0, 0xed, 0x6e, 0xe6, 0x73, 0xea,
	0xba, 0xc6, 0x09, 0xf6, 0xa1, 0xb3, 0x76, 0x3f, 0x50, 0xc6, 0x1c, 0x66, 0x10, 0x34, 0xa0, 0xbf,
	0x71, 0x29, 0x5b, 0x39, 0x1e, 0xfd, 0x68, 0xbb, 0x9e, 0xa1, 0x20, 0x82, 0x5e, 0x54, 0x66, 0xcb,
	0x77, 0x9f, 0x9c, 0xd5, 0xd2, 0x5e, 0x51, 0x43, 0x45, 0x1d, 0xc0, 0x5e, 0x79, 0x94, 0x95, 0x5d,
	0xda, 0xe4, 0x95, 0x34, 0xd2, 0xe1, 0x0a, 0x78, 0x06, 0x83, 0xa5, 0xb3, 0x70, 0x36, 0xde, 0x2d,
	0xcd, 0x10, 0x8c, 0xb2, 0xd4, 0x68, 0x24, 0x93, 0x17, 0xd0, 0x6b, 0xa8, 0x5d, 0xb0, 0xaf, 0x99,
	0xfd, 0x7e, 0xe6, 0xd1, 0x2f, 0xf3, 0xcb, 0x59, 0xf1, 0x1e, 0x1d, 0x60, 0xc1, 0x9c, 0xcd, 0xba,
	0xcc, 0xc9, 0x75, 0xf9, 0xfb, 0xbf, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x92, 0x51, 0xdb, 0x15,
	0x12, 0x04, 0x00, 0x00,
}
